// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, LM_GGML_TYPE_F16, LM_GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(128, LM_GGML_TYPE_F16, LM_GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(256, LM_GGML_TYPE_F16, LM_GGML_TYPE_F16);
